### ISSUE TITLE
Single GPU

### ISSUE THREAD

**Issue by dikapiliao1** [gyfastas/HCSC#4]
How to run classification tasks with a GPU

**Comment by gyfastas** [comment]
Hi! We have updated README.md and provide examples for linear classification evaluation on ImageNet and semi-supervised learning on ImageNet. 
For linear classification on ImageNet, run:
```
```
python3 eval_lincls_imagenet.py --data [your ImageNet Folder] \
--dist-url tcp://localhost:10001 --world-size 1 --rank 0 \
--multiprocessing-distributed 0 --gpu 0 \
--pretrained [your pre-trained model (example:out.pth)]
```

For semi-supervised learning on ImageNet, run:
```
python3 eval_semisup.py --labels_perc 1 \
--batch_size 256 --pretrained [your pretrained weights] \
[your ImageNet Folder]
```

Hope this instruction is helpful.

**Comment by dikapiliao1** [comment]
Thank you !

**Comment by dikapiliao1** [comment]
I am a novice. Can I use a GPU for pretraining on my own dataset?

**Comment by gyfastas** [comment]
> I am a novice. Can I use a GPU for pretraining on my own dataset?
Sure! You can set `--nproc_per_node=1`. For example:
```python3 -m torch.distributed.launch --master_port [your port] --nproc_per_node=1 \
pretrain.py [your ImageNet Folder]
```
Still, remember to modify the batch-size to 256 because it is the batch-size-per-gpu. I'm afraid that CUDA memory is not enough for batch-size 256 with single gpu. So I recommend using batch-size=128 and lr=0.015 following the instruction in https://github.com/facebookresearch/moco. Before pre-training on your own dataset, I think it would be helpful to reproduce the result on ImageNet with single gpu. Feel free to report if the down-stream performance is changed. I recommend to evaluate the pre-trained model with `eval_knn.py`.
